<a href="https://colab.research.google.com/github/Lekshmi-21/Project/blob/main/Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/study_performance.csv')
df

gender race_ethnicity parental_level_of_education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test_preparation_course  math_score  reading_score  writing_score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [77]:
df.head()

gender race_ethnicity parental_level_of_education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test_preparation_course  math_score  reading_score  writing_score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [78]:
df.tail()

gender race_ethnicity parental_level_of_education         lunch  \
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test_preparation_course  math_score  reading_score  writing_score  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86

In [79]:
df.dtypes

gender                         object
race_ethnicity                 object
parental_level_of_education    object
lunch                          object
test_preparation_course        object
math_score                      int64
reading_score                   int64
writing_score                   int64
dtype: object

In [80]:
df.isna().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [81]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns[:-1]:
    if df[i].dtypes==object:
        df[i]=le.fit_transform(df[i])
df

gender  race_ethnicity  parental_level_of_education  lunch  \
0         0               1                            1      1   
1         0               2                            4      1   
2         0               1                            3      1   
3         1               0                            0      0   
4         1               2                            4      1   
..      ...             ...                          ...    ...   
995       0               4                            3      1   
996       1               2                            2      0   
997       0               2                            2      0   
998       0               3                            4      1   
999       0               3                            4      0   

     test_preparation_course  math_score  reading_score  writing_score  
0                          1          72             72             74  
1                          0          69             90             88  
2                          1          90             95             93  
3                          1          47             57             44  
4                          1          76             78             75  
..                       ...         ...            ...            ...  
995                        0          88             99             95  
996                        1          62             55             55  
997                        0          59             71             65  
998                        0          68             78             77  
999                        1          77             86             86  

[1000 rows x 8 columns]

In [82]:
x=df.iloc[:,:-1].values
x

array([[ 0,  1,  1, ...,  1, 72, 72],
       [ 0,  2,  4, ...,  0, 69, 90],
       [ 0,  1,  3, ...,  1, 90, 95],
       ...,
       [ 0,  2,  2, ...,  0, 59, 71],
       [ 0,  3,  4, ...,  0, 68, 78],
       [ 0,  3,  4, ...,  1, 77, 86]])

In [83]:
y=df.iloc[:,-1].values
y

array([ 74,  88,  93,  44,  75,  78,  92,  39,  67,  50,  52,  43,  73,
        70,  58,  78,  86,  28,  46,  61,  63,  70,  53,  73,  80,  72,
        55,  75,  65,  75,  74,  61,  65,  38,  82,  79,  83,  59,  88,
        57,  54,  68,  65,  66,  54,  57,  62,  76,  76,  82,  48,  68,
        42,  75,  87,  43,  86,  49,  58,  10,  72,  34,  55,  71,  59,
        61,  37,  74,  56,  57,  73,  63,  48,  56,  41,  38,  22,  81,
        72,  68,  50,  45,  54,  63,  34,  82,  88,  74,  67,  82,  74,
        36,  71,  50,  92,  82,  62,  70,  62,  62,  67,  74,  89,  47,
        90,  72, 100,  64,  70,  72,  98,  49,  47,  54, 100,  74,  82,
        79,  61,  65,  89,  92,  93,  56,  73,  86,  67,  74,  74,  51,
        82,  40,  70,  84,  75,  48,  41,  56,  67,  69,  71,  64,  54,
        47,  78,  33,  75,  66,  81,  93,  69,  68,  66,  47,  61,  88,
        78,  60,  87,  64,  74,  85,  52,  49,  91, 100,  51,  78,  78,
        70,  74,  78,  81,  70,  54,  87,  58,  77,  62, 100,  7

In [84]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[ 1,  3,  0, ...,  0, 79, 82],
       [ 0,  2,  4, ...,  0, 67, 81],
       [ 1,  2,  4, ...,  1, 68, 68],
       ...,
       [ 0,  2,  0, ...,  1, 53, 62],
       [ 1,  2,  4, ...,  0, 50, 48],
       [ 0,  3,  0, ...,  1, 85, 91]])

In [85]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [86]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)


DecisionTreeClassifier()

In [87]:
from sklearn.model_selection import GridSearchCV
cls=DecisionTreeClassifier()
Parameter={'max_depth':[3,5,7,9],'class_weight':['balanced',None]}
gv=GridSearchCV(cls,Parameter,cv=10,scoring='accuracy')
gv.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:776: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(


GridSearchCV(cv=10, estimator=DecisionTreeClassifier(),
             param_grid={'class_weight': ['balanced', None],
                         'max_depth': [3, 5, 7, 9]},
             scoring='accuracy')

In [88]:
print(gv.best_params_)

{'class_weight': None, 'max_depth': 3}


In [89]:
cls1=DecisionTreeClassifier(max_depth=9,class_weight='balanced')
cls1.fit(x_train,y_train)
y_pred1=cls1.predict(x_test)
y_pred1

array([ 85,  67,  74,  74,  85,  74,  67,  56,  74,  48,  40,  23,  79,
        64,  79,  79,  48,  42,  56,  67,  74,  48,  77,  48,  79,  74,
        77,  56,  36,  56,  56,  56,  56,  74,  74,  48,  79,  74,  79,
        23,  77,  67,  56,  50,  85,  56,  67,  33,  85,  87,  77,  74,
        79,  56,  74,  74,  79,  48,  87,  94,  41,  85,  74,  56,  95,
        77,  74,  48,  56,  95,  56,  85,  56,  50,  56,  77,  85,  56,
        64,  48,  56,  40,  79,  74,  74,  67,  79,  67,  94,  23,  79,
        91,  56,  74,  28,  67,  56,  67,  79,  67,  79,  56,  50,  74,
        74,  67,  42,  79,  87,  56,  39,  87,  48,  50,  85,  56,  48,
        42,  67,  77,  64,  67,  79,  79,  56,  67,  77,  77,  42,  77,
        85,  74,  42, 100,  74,  39,  95,  87,  74,  48,  56,  67,  56,
        40,  77,  56,  34,  74,  48,  85,  79,  87,  67,  56,  95,  67,
        56,  74,  77,  48,  79,  56,  79,  56,  85,  74,  40,  91,  67,
        74,  87,  74,  95,  85,  42,  38,  48,  79,  95,  85,  6

In [91]:
score1=accuracy_score(y_test,y_pred)
score1

0.03333333333333333